export enum AbilitySubjects {
    DASHBOARD = 'Dashboard',
    LOGS = 'Logs',
    CLIENT = 'Client',
    CUSTOMERS = 'Customer',
    CORPORATE = 'Corporate',
    SERVICE = 'Service',
    COMPLANIT = 'Complaint',
    SUGGESTION = 'Suggestion',
    COMMENT = 'Comment',
    FEEDBACK = 'Feedback',
    SURVEY = 'Survey',
    STOCK = 'Stock',
    REPORT = 'Report',
    LOOKUOS = 'Lookups',
    ADMIN = 'Admin',
    ROLES = 'Roles',
  }