export enum AbilitySubjects {
    DASHBOARD = 'Dashboard',
    LOGS = 'Logs',
    CLIENT = 'Client',
    CUSTOMERS = 'Customer',
    CORPORATE = 'Corporate',
    SERVICE = 'Service',
    SERVICES = 'Services',
    COMPLANIT = 'Complaint',
    SUGGESTION = 'Suggestion',
    COMMENT = 'Comment',
    FEEDBACK = 'Feedback',
    SURVEY = 'Survey',
    STOCK = 'Stock',
    REPORT = 'Report',
    LOOKUOS = 'Lookups',
    ADMIN = 'Admin',
    ROLES = 'Roles',
    COMPLAINT_WORKFLOW = 'Complaints workflow',
    TASKS = 'Tasks',
    GIFT_VOCHER_STOCKS = 'Gift Voucher Stocks',
    VAS_STOCKS = 'VAS Stocks',
  }