export enum AbilitySubjects {
    DASHBOARD = 'Dashboard',
    CLIENT_MANAGEMENT = 'Clients Management',
    CUSTOMER_CARE_CENTER = 'Customer Care Center',
    SURVEY_MANAGEMENT = 'Survey Management',
    TASKS = 'Tasks',
    Complaints_Workflow = 'Complaints Workflow',
    STOCK_MANAGEMENT = 'Stock Management',
    REPORTING_ENGINE = 'Reporting Engine',
    LOOKUPS = 'Lookups',
    ADMIN = 'Admin',
    // ROLES = 'ROLES',
    // COMPLAINT_WORKFLOW = 'COMPLAINT_WORKFLOW',
    // TASKS = 'Tasks',
    // GIFT_VOCHER_STOCKS = 'Gift Voucher Stocks',
    // VAS_STOCKS = 'VAS Stocks',
  }